In [2]:
from dataclasses import replace

import pandas as pd

In [3]:
sr=pd.Series(["a","b","c"])

In [4]:
sr

0    a
1    b
2    c
dtype: str

In [5]:
sr1=pd.Series(["ahmad","python","class"],index=["*","=","!"])#optional perimeter index

In [6]:
sr1

*     ahmad
=    python
!     class
dtype: str

In [7]:
print("ahmad",end="")#print command perimeterr

ahmad

In [8]:
sr2=pd.Series(["val1","val2","val3"],index=["*","=","(_)"])
sr2

*      val1
=      val2
(_)    val3
dtype: str

In [9]:
di={"name":["ali","ahmad","arbab"],"age":[21,22,23]}
di

{'name': ['ali', 'ahmad', 'arbab'], 'age': [21, 22, 23]}

In [10]:
df=pd.DataFrame(di)#dataframe short variable

In [11]:
df

    name  age
0    ali   21
1  ahmad   22
2  arbab   23

In [12]:
df.to_csv("ClasFirstTable.csv")

In [13]:
dfItems=pd.read_excel("VendorProducts.xlsx")

In [14]:
dfItems

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,NaN,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,NaN,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,NaN,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,NaN,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,NaN,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [15]:
dfItems=pd.read_excel("VendorProducts.xlsx",sheet_name="Items")
dfItems

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,NaN,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,NaN,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,NaN,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,NaN,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,NaN,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [ ]:

print(dfItems["Item Name"])

In [18]:
dfItems=pd.read_excel("VendorProducts.xlsx",sheet_name="Collections")
dfItems

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Color,Secondary Color,Size,Unit Level,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"420,000د.ع",3145891072204,82528.0,100 مل,100 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"300,000د.ع",3145891072105,82755.0,50 مل,50 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك,The Glow Stick,#F3D5C6,"19,750د.ع",7333352079169,82570.0,24 سباركلينج بيج,24 Sparkling Beige,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك,The Glow Stick,#F2B2B9,"19,750د.ع",7333352079176,82571.0,25 روز جليم,25 Rose Gleam,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك,The Contour Stick,#AF8E7A,"19,750د.ع",7333352079084,82565.0,30,30,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل,Instant Anti Age Eraser Concealer 6 ml,#F5D4C5,"17,250د.ع",3600530733866,58724.0,03 معتدل,03 Fair,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"17,000د.ع",697029058770,60467.0,500 مل,500 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"6,500د.ع",697029602478,81429.0,88.7 مل,88.7 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"17,000د.ع",697029041260,47028.0,500 مل,500 ml,NaN,Level1,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"6,500د.ع",697029532409,81431.0,88.7 مل,88.7 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...

In [19]:
print(dfItems["Price"])

0        420,000د.ع
1        300,000د.ع
2         19,750د.ع
3         19,750د.ع
4         19,750د.ع
            ...
14481     17,250د.ع
14482     17,000د.ع
14483      6,500د.ع
14484     17,000د.ع
14485      6,500د.ع
Name: Price, Length: 14486, dtype: str

In [20]:
for i in dfItems["Price"]:
    print(int(i.replace("د.ع","").replace(",","")))

420000
300000
19750
19750
19750
19750
19750
19750
28750
28750
28750
35000
35000
35000
12000
12000
12000
12000
365500
600000
123250
152250
166750
129000
166750
123250
166750
129000
25000
25000
25000
25000
75500
93500
116250
170500
98250
98250
35000
15000
70000
70000
110000
110000
110000
76750
76750
23000
23000
23000
23000
23000
23000
15000
15000
14000
14000
14000
14000
67500
36500
65000
65000
65000
65000
65000
65000
7500
7500
7500
7500
7500
7500
7500
7500
7500
7500
7500
7500
7500
7500
7500
7500
7500
7500
7500
7500
43500
43500
46500
46500
43500
43500
46500
49500
46500
46500
46500
43500
46500
46500
46500
46500
46500
46500
46500
43500
49500
49500
43500
43500
43500
46500
46500
46500
49500
49500
49500
46500
49500
13250
13500
26000
26000
26000
26000
25000
25000
25000
25000
19000
19000
108500
33500
8000
8000
8000
12000
12000
12000
12000
15000
15000
15000
15000
6000
6000
6000
6000
6000
6000
6000
6000
6000
6000
6000
6000
6000
6000
6000
6000
6000
6000
6000
6000
8000
8000
8000
8000
8000
8000
8000
8000
28000
28000
28000
28000
28000
28000
28000
28000
28000
28000
28000
28000
28000
28000
28000
28000
28000
28000
28000
28000
40000
40000
40000
40000
40000
40000
40000
40000
40000
40000
40000
40000
40000
40000
40000
40000
40000
40000
40000
70000
70000
65000
65000
65000
65000
65000
65000
38000
38000
38000
38000
38000
38000
38000
40000
40000
40000
85750
85750
85750
100000
100000
100000
100000
100000
100000
100000
100000
100000
434000
542500
434000
542500
45000
45000
45000
25750
25750
68000
68000
68000
68000
68000
68000
20250
20250
20250
8000
8000
8000
143500
100000
28000
28000
28000
28000
28000
28000
28000
28000
21750
21750
21750
29500
29500
29500
29500
29500
29500
29500
29500
29500
29500
29500
29500
21750
21750
21750
21750
21750
21750
264000
168000
23000
23000
23000
23000
23000
23000
26000
26000
26000
23000
23000
23000
23000
30000
30000
35000
35000
35000
35000
35000
23000
23000
23000
22000
22000
22000
22000
22000
19000
19000
35000
35000
35000
35000
35000
35000
35000
25000
25000
25000
25000
24000
24000
18500
18500
18500
400000
682000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
133500
113250
42000
42000
42000
22000
22000
22000
22000
22000
22000
22000
22000
24000
24000
24000
24000
34000
41750
153000
212500
15500
15500
15500
15500
15000
15000
15000
15000
8500
8500
8500
8500
8500
8500
8500
8500
8500
8500
8500
8500
8500
8000
8000
8500
8500
8500
8500
8500
8500
9000
9000
9000
9000
9000
9000
9000
10000
10000
10000
10000
10000
10000
10000
10000
8500
8500
8500
9000
9000
9000
9000
9000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
15000
15000
10000
10000
20000
20000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
8000
8000
8000
6000
6000
6000
20000
10000
10000
15000
15000
10000
19500
19500
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
5000
5000
5000
10000
10000
10000
7000
7000
10000
10000
10000
10000
15000
15000
15000
15000
15000
15000
15000
15000
10000
10000
15000
15000
15000
15000
15000
15000
15000
15000
15000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
25000
25000
25000
25000
25000
25000
25000
25000
7000
10000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
108750
134500
131750
131750
131750
6250
6250
6250
6250
13250
13250
13250
13250
13250
13250
13250
13250
138000
114500
43500
43500
13000
13000
13000
13000
13000
13000
13000
13000
13000
13000
13000
11750
13750
20000
20000
20000
20000
20000
20000
20000
94000
94000
94000
94000
94000
94000
94000
94000
94000
94000
94000
70000
70000
70000
70000
70000
70000
70000
47750
47750
65250
65250
69750
69750
69750
54250
54250
54250
50750
54250
54250
62000
59000
59000
59000
84000
69750
90000
84000
84000
75000
75000
75000
75000
75000
75000
75000
75000
75000
75000
75000
75000
75000
75000
75000
38750
36250
36250
38750
36250
36250
36250
36250
36250
36250
36250
36250
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
65000
65000
62000
62000
62000
62000
55000
55000
55000
55000
55000
43500
43500
40500
40500
38000
38000
38000
38000
38000
38000
38000
38000
38000
38000
38000
38000
38000
38000
38000
38000
38000
55000
55000
59000
55000
55000
38000
38000
38000
38000
38000
38000
38000
38000
40000
40000
40000
40000
40000
40000
40000
40000
40000
40000
40000
40000
40000
45000
45000
45000
45000
45000
45000
45000
45000
40000
40000
40000
40000
40000
40000
40000
42000
42000
42000
42000
42000
40000
40000
42000
42000
42000
42000
32000
32000
32000
32000
50000
50000
50000
50000
50000
50000
8500
8500
8500
8500
8500
14250
14250
9750
9750
67000
66000
66000
15000
15000
15000
15000
13000
13000
13000
13000
81000
81000
58500
58500
58500
58500
58500
58500
73750
73750
98750
98750
98750
98750
98750
98750
98750
98750
98750
79250
79250
79250
79250
79250
79250
11000
11000
9000
9000
9000
9000
11000
11000
8000
9000
9000
10000
10000
10000
10000
10000
50500
50500
50500
50500
51250
25000
25000
25000
25000
25000
6250
5750
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
10000
10000
10000
8250
8250
4000
4000
7750
8000
8000
8500
8500
6000
6000
6000
6000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
5000
9750
10250
12750
12750
12750
9000
9000
7250
6750
7250
9750
10250
145000
158500
625000
435000
3250
3250
3250
3250
2750
2750
2500
108000
85250
24750
24750
24750
24750
10750
10750
10250
8000
8000
8000
8000
4000
4000
4000
5250
5250
4750
4750
4750
4750
7250
7250
7250
12500
12500
12500
12000
12000
12000
25000
25000
19500
19500
19500
19500
19500
19500
19500
19500
99500
99500
99500
99500
2000
2000
2000
5500
5500
5500
5500
21000
21000
21000
21000
21000
21000
21000
21000
21000
21000
29000
29000
29000
29000
29000
29000
29000
29000
29000
29000
16500
16500
16500
16500
16500
6750
6750
6750
6250
6250
8000
8000
5500
5500
6250
6250
6250
11000
11000
11000
11000
7000
7000
6250
6250
8250
10250
10000
10000
10000
10000
10000
10000
10000
6500
6500
6500
6500
6500
6500
6500
6500
6500
6500
6500
6500
6500
6500
6500
22500
22500
22500
12000
12000
12000
12000
12000
12000
12000
12000
12000
12000
12000
12000
12000
12000
12000
12000
12000
12000
12000
12000
2500
2500
2500
2500
2500
2500
2750
2750
2750
2750
2750
2750
2750
2750
2750
4500
4500
2500
2500
2500
2500
2500
2500
2500
2500
2500
194750
159500
3000
3000
3000
3500
3500
3500
3500
10000
10000
10000
10000
53000
53000
53000
55000
55000
55000
55000
41500
41500
41500
41500
41500
41500
19000
19000
19000
41500
41500
41500
41500
41500
41500
41500
41500
35000
35000
35000
35000
35000
35000
35000
35000
35000
35000
35000
35000
35000
35000
43500
43500
31000
31000
31000
31000
31000
31000
31000
31000
31000
31000
31000
31000
43500
43500
43500
43500
43500
34750
34750
34750
34750
34750
41000
41000
41000
41000
41000
41000
41000
41000
41000
41000
41500
41500
41500
41500
41500
41500
41500
41500
41500
41500
41500
41500
41500
41500
41500
41500
20250
20250
20250
20250
20250
20250
20250
20250
20250
8500
8500
12750
12750
12750
12750
11000
11000
14250
14250
14250
14250
12000
12000
9750
9750
9750
9750
9750
9750
9000
9000
9000
9000
8000
8000
8000
8000
7500
7500
7500
7500
7500
7500
7500
8000
8000
8000
8000
8000
68500
68500
68500
57500
57500
57500
9000
9000
9000
9000
7000
7000
7000
5000
5000
7500
7500
7500
7500
7500
7500
6000
6000
45000
45000
45000
45000
78250
78250
78250
78250
78250
78250
78250
78250
78250
65000
65000
65000
65000
65000
64500
64500
64500
64500
70000
70000
70000
70000
70000
70000
70000
70000
69000
69000
69000
93000
93000
93000
93000
93000
93000
93000
93000
92000
93000
93000
93000
93000
93000
92000
92000
92000
92000
92000
51000
51000
93000
93000
93000
93000
93000
93000
93000
93000
92000
92000
6750
6750
62000
55750
35750
35750
35750
35750
35750
36250
36250
0
0
0
38750
38750
15000
15000
15000
7250
7250
6500
7250
7250
7250
7250
7250
7250
9000
9000
7250
7250
7250
7250
7250
9000
7250
7250
7250
6500
7250
7250
9000
9000
7250
7250
9000
6500
7250
9000
7250
7250
7250
7250
9000
7250
7250
7250
7250
7250
7250
7250
7250
7250
9000
7250
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
9000
52000
52000
52000
84750
84750
77500
77500
72500
94500
94500
20750
20750
20750
29500
29500
29500
29500
29500
29500
28000
28000
28000
28000
28000
28000
28000
28000
28000
28000
31000
31000
31000
31000
31000
6000
6000
6000
6000
6000
6000
6000
25750
25750
25750
5500
5500
15000
15000
55000
55000
55000
88500
88500
90000
90000
90000
90000
90000
90000
73000
73000
62000
62000
62000
62000
62000
62000
62000
32000
32000
32000
35000
35000
35000
35000
35000
35000
35000
35000
35000
35000
35000
22750
22750
22750
22750
20000
20000
20000
20000
7000
7000
10000
10000
10000
10000
10000
10000
15000
15000
15000
179750
179750
144250
144250
144250
144250
144250
144250
144250
144250
144250
144250
144250
138250
97250
51000
51000
12000
12000
12000
12000
12000
12000
12000
12000
12000
12000
12000
12000
600000
426250
65000
49500
74750
51000
51000
425000
330000
83000
83000
83000
83000
83000
83000
83000
83000
83000
83000
83000
83000
83000
83000
35000
35000
10000
10000
10000
10000
10000
10000
10000
10000
68000
68000
68000
68000
68000
68000
68000
68000
68000
68000
68000
68000
68000
68000
68000
68000
68000
68000
68000
90500
90500
90500
6000
6000
6000
6000
6000
6000
6000
6000
6000
6000
6000
6000
6000
6000
6000
39000
39000
101000
101000
101000
12750
24000
24000
24000
24000
24000
24000
24000
24000
24000
24000
24000
24000
24000
24000
24000
24000
24000
25000
25000
25000
25000
25000
15000
15000
15000
15000
15000
15000
15000
15000
12000
12000
12000
12000
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
36500
24250
13000
13000
66750
66750
66750
66750
66750
66750
66750
66750
66750
66750
66750
66750
66750
66750
66750
66750
66750
66750
6750
6750
6750
6750
45000
45000
45000
45000
45000
45000
45000
13500
13500
25000
25000
25000
25000
25000
25000
25000
25000
25000
45000
10000
12000
12000
12000
50000
50000
6000
6000
25000
25000
25000
25000
25000
25000
15000
15000
15000
15000
15000
15000
30250
30250
30250
30250
30250
0
0
0
80000
80000
80000
80000
80000
8500
8500
8500
8500
8500
8500
8500
8500
8500
8500
8500
8500
8500
8500
8500
8500
8500
8500
8500
8500
8500
8500
8500
8500
8500
8500
33250
22250
33250
22250
33250
22250
22250
21000
26500
33500
22250
22250
22250
22250
31000
16500
18750
8750
8750
8750
9250
9250
9250
3500
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
7750
18500
18500
18500
8500
8500
8500
8500
8500
8500
8500
8500
8000
8000
8000
8000
8000
16500
16500
15000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
40000
40000
40000
40000
40000
40000
40000
40000
40000
40000
40000
40000
9000
9000
9000
26250
13000
26250
26250
26250
14000
26250
26250
26250
13500
22500
32500
62000
32500
32500
32500
32500
32500
32500
17000
15500
38750
16500
31000
15500
16500
16500
26250
26250
16000
26250
17000
16000
15500
26250
26250
17000
17000
16500
17000
16000
23000
23000
23000
9000
9000
15000
15000
15000
15000
15000
15000
25000
18000
10000
10000
10000
10000
10500
10000
9500
9500
9500
9500
9500
9500
9500
9500
9500
9500
13250
13250
13250
13250
13250
10750
0
0
0
0
10000
10000
10000
10000
10000
10000
10000
10000
69750
59750
85250
0
0
28750
28750
28750
28750
28750
28750
28750
28750
28750
28750
0
0
0
0
0
0
0
0
9500
9500
9500
9500
9500
9500
8000
8000
16500
15000
16500
16500
15000
15000
20000
17000
13000
13000
13000
13000
10500
14000
17000
17000
17000
13000
13000
12000
12000
12000
15000
12000
12000
12000
12000
12000
12000
12000
12000
12000
32000
32000
32000
32000
32000
32000
32000
32000
32000
32000
32000
32000
32000
32000
32000
32000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
29000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
26000
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
7250
7250
7250
7250
7250
7250
7250
7250
7250
7250
7250
66750
0
0
0
10000
10000
10000
8000
8000
0
0
0
0
0
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
6250
15500
15500
0
0
0
0
0
0
9500
9500
9500
9500
9500
9500
18500
18500
18500
18500
18500
6250
6250
8000
8000
10000
10000
10000
10000
10000
34000
0
0
0
0
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
0
0
0
0
0
0
0
0
0
0
31000
31000
31000
31000
23500
16750
8000
8000
10750
10750
10750
10750
10750
10750
10750
10750
10750
10750
2500
2500
23250
23250
23250
15500
15500
15500
15500
15500
15500
15500
15500
15500
10000
10000
18500
18500
6000
18500
18500
18500
18500
18500
18500
18500
18500
18500
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
9000
9000
10000
9000
18500
18500
18500
18500
16000
16000
16000
16000
25750
25750
25750
15500
26250
15000
18500
18500
21500
18500
18500
19500
25750
25750
25750
25750
25750
25750
25750
6750
6750
6750
6750
6750
6750
31000
31000
31000
31000
31000
31000
37250
37250
37250
37250
37250
37250
15000
15000
15000
15000
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
503750
255750
13000
13000
13000
13000
13000
13000
19500
19500
19500
19500
19500
19500
19500
0
0
775000
255750
22750
22750
22750
22750
22750
22750
1007500
480500
23250
0
0
20000
20000
20000
20000
20000
27750
44000
14500
31000
31000
0
0
0
0
13250
31000
18500
18500
18500
18500
18500
18500
18500
18500
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
12500
12500
12500
12500
12500
12500
12500
12500
31000
31000
31000
10250
10250
9750
8250
10250
10250
10250
31000
31000
31000
31000
31000
31000
503750
255750
697500
356500
22000
22000
22000
22000
22000
22000
22000
22000
22000
22000
11000
22000
22000
11000
22000
22000
10250
11000
11000
11000
11000
11000
15000
28000
19000
22250
22250
22250
22250
27250
27250
27250
27250
27250
27250
27250
27250
27250
27250
27250
27000
27000
27000
27000
27000
18500
18500
18500
18500
18500
18500
18500
18500
18500
18500
18500
18500
18500
18500
18500
18500
18500
18500
13250
14500
23250
23250
23250
21500
21500
22000
22000
22000
22000
22000
22000
15500
15500
15500
15500
15500
15500
15500
15500
15500
15500
22000
22000
22000
18000
18000
8750
8750
8750
8750
8750
8750
8750
8750
8750
8750
30250
15250
15250
15250
12500
12500
12500
12500
10000
10000
10000
16500
15250
16500
18750
18750
18750
18750
11750
11750
11750
11750
11750
21250
20000
21250
10750
10750
10750
10750
10750
10750
10750
10750
10750
10750
17250
17250
17250
18750
18500
18500
18500
18500
18500
18500
20500
20500
20500
18000
18000
18000
18000
26500
26500
26250
26250
26250
26250
26250
26250
26250
15500
12000
30500
30500
30500
30500
30500
30500
30500
25000
24750
25000
69750
69750
69750
11250
11250
22500
22500
32750
32750
32750
25000
25000
25000
25000
25000
25000
25000
25000
25000
25000
155000
77500
39750
20500
20500
20500
20500
20500
229000
118500
27750
155000
77500
14500
16500
13500
13500
13500
13500
13500
13500
13500
13500
13500
13500
13500
13500
13500
13500
13500
248000
93000
155000
130750
13250
11000
11000
11000
38750
31000
22250
22250
22250
22250
49500
46500
30000
32000
8250
8250
8250
54250
59000
10000
10000
10000
34750
48250
49250
11750
11750
12750
11750
12750
11000
11750
11750
12750
11750
24750
24750
24750
24750
24750
24750
24750
22000
23250
23250
23250
18750
18750
18750
18750
18750
20000
18750
9500
9500
9500
9500
9500
9500
9500
9500
9500
9500
16500
16500
116250
147250
121000
74500
23750
23750
23750
23750
23750
23750
23750
23750
63500
49500
15000
15000
15000
15000
15000
15250
15250
15250
3500
3500
3500
3500
55000
70000
11750
11750
16500
16500
16500
24750
62000
6250
24250
24250
93000
69750
131750
9500
9500
9500
9500
26750
22000
22000
22000
22000
22000
22000
22000
22000
22000
22000
22000
22000
22000
22000
22000
22000
22000
80500
62000
18750
18750
18750
122500
31250
31250
10250
10250
20500
20500
20500
20500
46500
46500
16500
16500
16500
16500
16500
16500
16500
16500
16500
20750
20750
20750
20750
20750
20750
16500
16500
16500
229000
118500
10750
10750
310000
130750
28500
28500
28500
28000
28000
77500
100750
65000
4750
4750
4750
4750
4750
4750
4750
4750
4750
4750
4750
4750
4750
4750
4750
4750
4750
4750
4750
4750
24250
24250
24250
24250
24250
24250
24250
24250
65000
43500
15000
232500
178250
12000
12000
12000
12000
12000
10000
10000
10000
10000
69750
69750
10250
10250
15500
229000
118500
3500
6000
6000
3500
3500
3500
3500
3500
3500
6000
3500
3500
6000
3500
3500
6000
3500
6000
6000
6000
3500
6000
6000
6000
6000
6000
6000
6000
6000
6000
6000
3500
3500
6000
6000
6000
6000
6000
155000
130750
6500
6500
6500
6500
6500
6500
6500
6500
6500
6500
3000
3000
3000
3000
3000
3000
3000
8000
8000
8000
8000
8500
7500
7500
7500
7500
7500
7500
43500
43500
43500
33000
43500
43500
6000
6000
6000
8500
8500
8500
8500
3500
3500
3500
3500
3500
3500
3500
3500
3500
3500
3500
3500
3500
3500
3500
3500
3500
3500
3500
3500
3500
3500
3500
3500
8000
8000
8000
8000
8000
8000
8000
8000
93000
96000
91500
9000
77500
108500
11000
11000
11000
9750
9750
9750
9750
9750
9750
9750
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
131750
90000
54250
80500
7000
7000
7000
7500
7500
7500
9750
74500
54250
4500
4500
10000
10000
7500
7500
7500
7500
85250
59000
8500
8500
8500
8500
8000
6000
6000
6750
6750
35000
30000
5000
5000
7000
7000
7000
7000
7500
7500
5000
5000
5000
5000
5000
5000
5000
45000
45000
45000
45000
45000
45000
45000
45000
45000
45000
45000
5750
5750
5750
5000
5000
5000
5000
5000
5000
5000
5000
5000
10000
10000
10000
4000
4000
4000
4000
4000
4000
4000
20250
20250
7500
7500
7500
7500
7500
8500
7500
6000
6000
6000
5000
5000
5000
5000
7000
7000
7000
7000
7000
7000
7000
7000
7000
7000
7000
6000
6000
6000
7250
7250
7250
7250
7000
7000
7000
7000
7000
12750
12750
12750
12750
12750
12750
12750
6000
6000
6000
6000
6000
6000
6500
6000
6000
6000
6000
6000
6000
6000
8000
8000
8000
8000
7000
7000
7000
7000
7000
7000
7000
12500
12500
12500
12500
12500
6000
6000
10000
10000
10000
10000
10000
5000
5000
5000
7000
7000
9250
9250
12750
12750
7000
7000
9500
9500
9500
14000
14000
14000
14000
14000
14000
10000
10000
9250
9250
9250
4000
4000
4000
4500
4000
4000
4000
4000
4000
4000
4000
4000
4000
15000
15000
15000
6000
5500
7000
7000
7000
9250
9250
9250
9250
6000
6000
8500
8500
8500
8500
8500
8500
6250
6250
6250
6250
6250
6250
6500
6250
6250
6250
6250
6250
6250
6250
11000
11000
11000
11000
11000
11000
26250
26250
26250
26250
26250
12500
12500
12500
12500
12500
15500
15500
15500
15500
14500
14500
15500
15500
15500
32500